# Site settings
title: raym
email: noemail@raym.github.io
description: "a tale of going full wizard"

# Build settings
kramdown:
  input: GFM #Github Flavour'd Markdown
highlighter: pygments

permalink: pretty

#gems: [jekyll-assets]

#assets:
  #sources:
    #- _assets/images
    #- _assets/javascripts
    #- _assets/stylesheets
    #- _vendors/javascripts
    #- _vendors/stylesheets
    #- _vendors/foundation
    #- _vendors/swagger

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
